
import { render } from './core/renderer';
import { createElement } from './core/createElement';
import { Fragment } from './core/Fragment';
import { registerComponent, unregisterComponent, getComponent, clearComponents } from './core/componentRegistry';
import { 
  Audio, 
  Bold, 
  CaptionedParagraph, 
  Code,
  Document,
  ExampleInput,
  ExampleOutput,
  ExampleSet,
  FileTree, 
  Header,
  Hint,
  Image,
  Inline,
  Introducer,
  DataObject,
  OutputFormat,
  Question,
  Role,
  StepwiseInstructions,
  Table,
  Task,
  type AudioProps,
  type BoldProps,
  type CaptionedParagraphProps,
  type CodeProps,
  type DocumentProps,
  type ExampleInputProps,
  type ExampleOutputProps,
  type ExampleSetProps,
  type HeaderProps,
  type HintProps,
  type ImageProps,
  type InlineProps,
  type IntroducerProps,
  type ObjectProps,
  type OutputFormatProps,
  type QuestionProps,
  type RoleProps,
  type StepwiseInstructionsProps,
  type TableProps,
  type TaskProps
} from './components';
import { epomlparse } from './core/epomlparse';
import { type TemplateVariables, type Component } from './types';

// Export the core functions, components, epomlparse function, and component registry functions
export { 
  render,
  createElement,
  Fragment,
  Component,
  Audio, 
  Bold, 
  CaptionedParagraph, 
  Code,
  Document,
  ExampleInput,
  ExampleOutput,
  ExampleSet,
  FileTree, 
  Header,
  Hint,
  Image,
  Inline,
  Introducer,
  DataObject,
  OutputFormat,
  Question,
  Role,
  StepwiseInstructions,
  Table,
  Task,
  epomlparse, 
  registerComponent, 
  unregisterComponent, 
  getComponent, 
  clearComponents,
  type AudioProps,
  type BoldProps,
  type CaptionedParagraphProps,
  type CodeProps,
  type DocumentProps,
  type ExampleInputProps,
  type ExampleOutputProps,
  type ExampleSetProps,
  type HeaderProps,
  type HintProps,
  type ImageProps,
  type InlineProps,
  type IntroducerProps,
  type ObjectProps,
  type OutputFormatProps,
  type QuestionProps,
  type RoleProps,
  type StepwiseInstructionsProps,
  type TableProps,
  type TaskProps,
  type TemplateVariables
};
