import { render } from './core/renderer';
import { createElement } from './core/createElement';
import { Fragment } from './core/Fragment';
import { registerComponent, unregisterComponent, getComponent, clearComponents } from './core/componentRegistry';
import { 
  Audio, 
  Bold, 
  CaptionedParagraph, 
  Code,
  Document,
  Example,
  ExampleInput,
  ExampleOutput,
  ExampleSet,
  FileTree, 
  Header,
  Hint,
  Image,
  Inline,
  Introducer,
  DataObject,
  OutputFormat,
  Question,
  Role,
  StepwiseInstructions,
  Table,
  Task,
  // Newly added components
  Italic,
  Text,
  Paragraph,
  Strikethrough,
  Underline,
  Newline,
  List,
  ListItem,
  SubContent,
  Folder,
  Webpage,
  Conversation,
  AiMessage,
  HumanMessage,
  SystemMessage,
  MessageContext,
  ToolRequest,
  ToolResponse,
  type AudioProps,
  type BoldProps,
  type CaptionedParagraphProps,
  type CodeProps,
  type DocumentProps,
  type ExampleProps,
  type ExampleInputProps,
  type ExampleOutputProps,
  type ExampleSetProps,
  type HeaderProps,
  type HintProps,
  type ImageProps,
  type InlineProps,
  type IntroducerProps,
  type ObjectProps,
  type OutputFormatProps,
  type QuestionProps,
  type RoleProps,
  type StepwiseInstructionsProps,
  type TableProps,
  type TaskProps,
  // Newly added component types
  type ItalicProps,
  type TextProps,
  type ParagraphProps,
  type StrikethroughProps,
  type UnderlineProps,
  type NewlineProps,
  type ListProps,
  type ListItemProps,
  type SubContentProps,
  type FolderProps,
  type WebpageProps,
  type ConversationProps,
  type AiMessageProps,
  type HumanMessageProps,
  type SystemMessageProps,
  type MessageContextProps,
  type ToolRequestProps,
  type ToolResponseProps
} from './components';
import { epomlparse } from './core/epomlparse';
import { type TemplateVariables, type Component } from './types';

// Export the core functions, components, epomlparse function, and component registry functions
export { 
  render,
  createElement,
  Fragment,
  Component,
  Audio, 
  Bold, 
  CaptionedParagraph, 
  Code,
  Document,
  Example,
  ExampleInput,
  ExampleOutput,
  ExampleSet,
  FileTree, 
  Header,
  Hint,
  Image,
  Inline,
  Introducer,
  DataObject,
  OutputFormat,
  Question,
  Role,
  StepwiseInstructions,
  Table,
  Task,
  // Newly added components
  Italic,
  Text,
  Paragraph,
  Strikethrough,
  Underline,
  Newline,
  List,
  ListItem,
  SubContent,
  Folder,
  Webpage,
  Conversation,
  AiMessage,
  HumanMessage,
  SystemMessage,
  MessageContext,
  ToolRequest,
  ToolResponse,
  epomlparse, 
  registerComponent, 
  unregisterComponent, 
  getComponent, 
  clearComponents,
  type AudioProps,
  type BoldProps,
  type CaptionedParagraphProps,
  type CodeProps,
  type DocumentProps,
  type ExampleProps,
  type ExampleInputProps,
  type ExampleOutputProps,
  type ExampleSetProps,
  type HeaderProps,
  type HintProps,
  type ImageProps,
  type InlineProps,
  type IntroducerProps,
  type ObjectProps,
  type OutputFormatProps,
  type QuestionProps,
  type RoleProps,
  type StepwiseInstructionsProps,
  type TableProps,
  type TaskProps,
  // Newly added component types
  type ItalicProps,
  type TextProps,
  type ParagraphProps,
  type StrikethroughProps,
  type UnderlineProps,
  type NewlineProps,
  type ListProps,
  type ListItemProps,
  type SubContentProps,
  type FolderProps,
  type WebpageProps,
  type ConversationProps,
  type AiMessageProps,
  type HumanMessageProps,
  type SystemMessageProps,
  type MessageContextProps,
  type ToolRequestProps,
  type ToolResponseProps,
  type TemplateVariables
};